/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('./src/components/AButton/AButton.vue')['default']
    Button: typeof import('./src/components/Button/Button.vue')['default']
    Header: typeof import('./src/components/Header/Header.vue')['default']
  }
}
